---
version: "3.8"

services:
  filebeat:
    image: luzblu3s/filebeat:8.5.3
    user: root
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
    command: -e -strict.perms=false
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    deploy:
      mode: global

configs:
  filebeat_config:
    name: filebeat_config-${CONFIG_NUMBER:-0}
    file: config/filebeat.yml