http:
  routers:
    traefik:
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: api@internal
      entryPoints:
        - web

    kibana_http:
      rule: "Host(`{{ env "KIBANA_URL" }}`)"
      service: kibana
      entrypoints:
        - web
      middlewares:
        - redirect_https

    kibana_https:
      rule: "Host(`{{ env "KIBANA_URL" }}`)"
      service: kibana
      entrypoints:
        - websecure
      tls:
        {}

    elasticsearch_http:
      rule: "Host(`{{ env "ELASTICSEARCH_URL" }}`)"
      service: elasticsearch
      entrypoints:
        - web

    kibana_5601:
      rule: "HostRegexp(`{subhost:[a-zA-Z0-9-]+}.{{ env "DOMAIN" }}`)"
      service: kibana
      entrypoints:
        - kibana
      # middlewares:
      #   - kibanaForward


    elasticsearch_9200:
      rule: "HostRegexp(`{subhost:[a-zA-Z0-9-]+}.{{ env "DOMAIN" }}`)"
      service: elasticsearch
      entrypoints:
        - elasticsearch


  services:
    kibana:
      loadBalancer:
        servers:
          - url: "http://tasks.kibana:5601/"
        healthCheck:
          path: /
          port: 5601

    elasticsearch:
      loadBalancer:
        servers:
          - url: "http://tasks.coordinator:9200/"
          - url: "http://tasks.master-1:9200/"
          - url: "http://tasks.master-2:9200/"
          - url: "http://tasks.master-3:9200/"
        healthCheck:
          path: /_cat/health
          port: 9200

  
  middlewares:
    redirect_https:
      redirectScheme:
        scheme: https
        permanent: true

    kibanaForward:
      redirectRegex:
        regex: .*
        replacement: http://{{ env "KIBANA_URL" }}
        # replacement: https://{{ env "KIBANA_URL" }}
        permanent: true


serversTransport:
  insecureSkipVerify: true


tls:
  certificates:
    - certFile: /run/secrets/konicki.com.pem
      keyFile: /run/secrets/konicki.com.key
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: /run/secrets/konicki.com.pem
        keyFile: /run/secrets/konicki.com.key

  options:
    default:
      minVersion: VersionTLS12