---
version: "3.8"

services:
  kibana:
    image: luzblu3s/kibana:8.5.3
    networks:
      - elasticsearch
      - traefik
    environment:
      SERVER_NAME: ${KIBANA_URL}
      ELASTICSEARCH_HOSTS: http://tasks.coordinator:9200
      SERVER_PUBLICBASEURL: http://${KIBANA_URL}:5601
      XPACK_MONITORING_COLLECTION_ENABLED: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.elasticsearch == true
      restart_policy:
        condition: ${DOCKER_DEFAULT_RESTART_POLICY}
        delay: ${DOCKER_DEFAULT_DELAY}
        max_attempts: ${DOCKER_DEFAULT_MAX_ATTEMPTS}


networks:
  elasticsearch:
    driver: overlay
    attachable: true
  traefik:
    external: true
