---
version: "3.8"

services:
  kibana:
    image: luzblu3s/kibana:8.5.3
    networks:
      - elasticsearch
      - traefik
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200" # Loadbalanced by the Traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3


networks:
  elasticsearch:
    external: true
  traefik:
    external: true
