---
parameters:
  - name: environments
    type: object
    default: 
      prod: vm1.konicki.com


stages:
- ${{ each env in parameters.environments }}:
  - template: stage/ado/containerized/template.yml@Templates
    parameters:
      stageDisplayName: ElasticSearch on ${{ upper(env.key) }}
      dependsOn: []
      environment: ${{ upper(env.key) }}
      pool: K0nicki
      server: ${{ env.value }}
      steps:
        - script: |
            set -o allexport
            source ../env/elasticsearch.env
            source ../env/traefik.env
            set +o allexport

            docker network create --driver overlay traefik

            docker stack deploy --compose-file=docker-compose.elasticsearch.yml --compose-file=docker-compose.kibana.yml --with-registry-auth --prune elasticsearch
          workingDirectory: "$(Build.Repository.LocalPath)/elasticsearch"
          env:
            DOCKER_CONTEXT: ${{ env.value }}
          displayName: Deploy ElastiSearch stack
